# Generated by Django 4.1.7 on 20-04-2023 by PSB

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('Grievence', 'Grievence'), ('Suggestions', 'Suggestions'), ('Wishes', 'Wishes')], default='Meeting', max_length=50),
        ),
    ]
